apiVersion: v1
kind: Service
metadata:
  name: pet-detection-service
spec:
  selector:
    app: pet-detection-service
  type: LoadBalancer
  ports:
    - name: pet-detection-service
      port: 3000
      targetPort: 3000
